services:
  frontend:
    build: ./Frontend
    container_name: transcendence_front
    expose:
      - "3000"

  backend:
    build: ./backend
    container_name: transcendence_back
    ports:
      - "4000:4000"
    expose:
      - "4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads

  nginx:
    image: nginx:stable-alpine
    container_name: transcendence_nginx
    ports:
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:15
    container_name: transcendence_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  uploads_data:
